kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: git.znedw.com/znedw/samba
      registry: git.znedw.com
      password:
         from_secret: password
      username:
         from_secret: username
      tags: latest

trigger:
 branch:
    - master
  event:
    - push