name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest # todo, this is for docker binary
    steps:
      - 
        name: Checkout
        uses: https://github.com/actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      -
        name: Login to Gitea Packages
        uses: docker/login-action@v3
        with:
          registry: https://git.znedw.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - 
        name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.znedw.com/znedw/samba:${{gitea.sha}},git.znedw.com/znedw/samba:latest"
